# Generated by Django 4.1.1 on 2022-09-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
